# Generated by Django 5.1.1 on 2024-09-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_count_of_views_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_of_views",
            field=models.IntegerField(default=0),
        ),
    ]
